{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = with pkgs; [
    nodejs_22
    yarn
    pkg-config
    python3
    git

    stdenv.cc.cc.lib
    glib
    gtk3
    atk
    at-spi2-atk
    cairo
    pango
    gdk-pixbuf
    dbus
    nss
    nspr
    expat
    libdrm
    libgbm
    mesa
    cups
    alsa-lib
    libnotify
    xorg.libX11
    xorg.libXcomposite
    xorg.libXcursor
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXi
    xorg.libXrandr
    xorg.libXrender
    xorg.libXScrnSaver
    xorg.libXtst
    xorg.libxcb
    xorg.libxshmfence
    xorg.libXxf86vm
    xorg.libxkbfile
    xorg.libXinerama
    xorg.libXau
    xorg.libXdmcp
    xorg.libICE
    xorg.libSM
    xorg.libXt
    xorg.libXv
    xorg.libXmu
    xorg.libXpm
    libxkbcommon
    xorg.xcbutil
    xorg.xcbutilimage
    xorg.xcbutilkeysyms
    xorg.xcbutilrenderutil
    xorg.xcbutilwm
    libGL
    libGLU
    udev
  ];

  shellHook = ''
    export LD_LIBRARY_PATH="${pkgs.lib.makeLibraryPath [
      pkgs.stdenv.cc.cc.lib
      pkgs.glib
      pkgs.gtk3
      pkgs.atk
      pkgs.at-spi2-atk
      pkgs.cairo
      pkgs.pango
      pkgs.gdk-pixbuf
      pkgs.dbus
      pkgs.nss
      pkgs.nspr
      pkgs.expat
      pkgs.libgbm
      pkgs.libdrm
      pkgs.mesa
      pkgs.cups
      pkgs.alsa-lib
      pkgs.libnotify
      pkgs.xorg.libX11
      pkgs.xorg.libXcomposite
      pkgs.xorg.libXcursor
      pkgs.xorg.libXdamage
      pkgs.xorg.libXext
      pkgs.xorg.libXfixes
      pkgs.xorg.libXi
      pkgs.xorg.libXrandr
      pkgs.xorg.libXrender
      pkgs.xorg.libXScrnSaver
      pkgs.xorg.libXtst
      pkgs.xorg.libxcb
      pkgs.xorg.libxshmfence
      pkgs.xorg.libXxf86vm
      pkgs.xorg.libxkbfile
      pkgs.xorg.libXinerama
      pkgs.xorg.libXau
      pkgs.xorg.libXdmcp
      pkgs.xorg.libICE
      pkgs.xorg.libSM
      pkgs.xorg.libXt
      pkgs.xorg.libXv
      pkgs.xorg.libXmu
      pkgs.xorg.libXpm
      pkgs.libxkbcommon
      pkgs.xorg.xcbutil
      pkgs.xorg.xcbutilimage
      pkgs.xorg.xcbutilkeysyms
      pkgs.xorg.xcbutilrenderutil
      pkgs.xorg.xcbutilwm
      pkgs.libGL
      pkgs.libGLU
      pkgs.udev
    ]}:$LD_LIBRARY_PATH"
  '';
}
